apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: desafio
spec:
  selector:
    app: minsait
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
