apiVersion: v1
kind: Service
metadata:
  name: minsait-service
  namespace: desafio
spec:
  selector:
    app: minsait
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
